M48
; DRILL file {KiCad 9.0.5} date 2026-05-07T09:13:55-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-07T09:13:55-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.048
%
G90
G05
T1
X140.5Y-46.98
X140.5Y-63.5
T2
X173.847Y-52.66
M30
